theme: jekyll-theme-cayman

title: SP-29 Green: A Spotify Recommendation App for iOS and Android

show_downloads: true

ProjectPlan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

ProjectVideo:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

ProjectPlan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D
