theme: jekyll-theme-cayman

Project Plan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

Project Video:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

Project Plan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D
