theme: jekyll-theme-cayman

title: SP-29 Green: A Spotify Recommendation App for iOS and Android

Project Plan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

Project Video:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D

Project Plan:
  repository_url: https://www.youtube.com/watch?v=SPpFcIOktLY&pp=ygUcaG93IHRvIHByb25vdW5jZSBwbGFjZWhvbGRlcg%3D%3D
